fragment PostParts on Post {
  __typename
  title
  body
}

fragment PageParts on Page {
  __typename
  ... on PageHome {
    hero {
      __typename
      eyebrow
      headline
      sub
      primaryButtonText
      primaryButtonHref
    }
    philosophyTabs {
      __typename
      rightMoment {
        __typename
        tabTitle
        topEyebrow
        eyebrow
        headline
        definition
        weightPoints {
          __typename
          icon
          text
        }
        quoteIntro
        quoteCallout
        quoteOutro
      }
      builtDifferently {
        __typename
        tabTitle
        label
        headline
        leadParagraph
        principles {
          __typename
          icon
          text
        }
        pullQuoteIntro
        pullQuoteCallout
      }
      investmentPhilosophy {
        __typename
        tabTitle
        label
        headline
        options {
          __typename
          title
          description
          bullets
          isHighlighted
        }
      }
    }
    how {
      __typename
      backgroundColor
      label
      headline
      description
      steps {
        __typename
        number
        icon
        title
        body
      }
      throughline
    }
    partnership {
      __typename
      headline
      criteriaLabel
      criteriaItems {
        __typename
        icon
        title
        description
      }
      promiseLabel
      promiseItems {
        __typename
        icon
        title
        description
      }
      bottomLine1
      bottomLine2
    }
    cta {
      __typename
      backgroundColor
      headline
      sub
      buttonText
      contactEmail
    }
  }
  ... on PageDefault {
    title
    body
  }
}
